Bag of words

In [2]:
import numpy as np  
import pandas as pd

In [3]:
df = pd.DataFrame({"text": ["people watch youtube", "youtube watch youtube", "people write comments", "yoututbe write comments"], "output":[1,1,0,0]})

In [4]:
df

text  output
0     people watch youtube       1
1    youtube watch youtube       1
2    people write comments       0
3  yoututbe write comments       0

In [7]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()


In [8]:
bow = cv.fit_transform(df['text'])
print(cv.vocabulary_)

{'people': 1, 'watch': 2, 'youtube': 4, 'write': 3, 'comments': 0, 'yoututbe': 5}


In [10]:
bow.toarray()

array([[0, 1, 1, 0, 1, 0],
       [0, 0, 1, 0, 2, 0],
       [1, 1, 0, 1, 0, 0],
       [1, 0, 0, 1, 0, 1]])

In [11]:
cv.transform(['vamshi watch youtube']).toarray()

array([[0, 0, 1, 0, 1, 0]])

In [12]:
x=bow.toarray()
y=df['output']

Ngrams

In [13]:
df = pd.DataFrame({"text": ["people watch youtube", "youtube watch youtube", "people write comments", "yoututbe write comments"], "output":[1,1,0,0]})

In [14]:
# BI grams
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(2,2)) #3x3

In [15]:
bow = cv.fit_transform(df['text'])
print(cv.vocabulary_)

{'people watch': 0, 'watch youtube': 2, 'youtube watch': 4, 'people write': 1, 'write comments': 3, 'yoututbe write': 5}


TFIDF

In [16]:
df = pd.DataFrame({"text":["people watch dswithbappy",
                         "dswithbappy watch dswithbappy",
                         "people write comment",
                          "dswithbappy write comment"],"output":[1,1,0,0]})

df

text  output
0       people watch dswithbappy       1
1  dswithbappy watch dswithbappy       1
2           people write comment       0
3      dswithbappy write comment       0

In [17]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfid = TfidfVectorizer()

arr = tfid.fit_transform(df['text']).toarray()
arr

array([[0.        , 0.49681612, 0.61366674, 0.61366674, 0.        ],
       [0.        , 0.8508161 , 0.        , 0.52546357, 0.        ],
       [0.57735027, 0.        , 0.57735027, 0.        , 0.57735027],
       [0.61366674, 0.49681612, 0.        , 0.        , 0.61366674]])

In [ ]:
print(tfid.idf_)